### ISSUE TITLE
[IW6X] Combat training seems to be stuck on regular/mixed afaik how can you change to be recruit or other difficulty options

### ISSUE THREAD

**Issue by VelirzX** [mxve/alterware-launcher#125]
Playing combat training and im noticing diffrent levels for the bots some higher, some lower could there be an option to change difficulty or not? bot_difficulty does nothing.

**Comment by mxve** [comment]
Visit the [AlterWare Forum](https://forum.alterware.dev/) or [Discord](https://discord.gg/2ETE8engZM) for support.

**Comment by LeRutY** [comment]
I just played around with the "bot_difficultydefault" setting, didn´t change the bots like mentioned. But somehow the bots were all level 60 for at least the next combat training match after doing a full one in private. Must have been a glitch. Can´t reproduce it in Ghosts or AW

**Comment by VelirzX** [comment]
> I just played around with the "bot_difficultydefault" setting, didn´t change the bots like mentioned. But somehow the bots were all level 60 for at least the next combat training match after doing a full one in private. Must have been a glitch. Can´t reproduce it in Ghosts or AW

Easiest way to reproduce is to start a match in combat training that's how. Unless the levels are visual I'm pretty sure they aren't and are tied to the difficulties you pick.
