### ISSUE TITLE
Launcher crashes when downloading file that already exists

### ISSUE THREAD

**Issue by pickles976** [mxve/alterware-launcher#135]
It appears that there is a "bug" when the alterware launcher tries to download a file that already exists in the user's filesystem.

The problem looks like it occurs at [line 46 of http_async.rs](https://github.com/mxve/alterware-launcher/blob/main/src/http_async.rs#L46)

Could we prompt the user to overwrite their local file if we find that a file already exists? The current way that rust handles the error looks like a crash to users that aren't running the exe file from the command line.

I am a Rust noob, but would be willing to implement this fix myself if it is an acceptable solution.

#### Error:

```
[Downloading] F:/Games/Call of Duty Modern Warfare 2/iw4x/video/IW_logo.bik (10.04MB)
⠁ IW_logo.bik > 0 B/10.04 MiB | 0 B/s | 0s                                                                              thread 'main' panicked at src/main.rs:270:13:
Failed to create file 'F:\Games\Call of Duty Modern Warfare 2\iw4x/video/IW_logo.bik'
```

#### Solution: 

Manually delete `F:/Games/Call of Duty Modern Warfare 2/iw4x/video/IW_logo.bik`

#### Notes:

Also crashes for the following files, with the same solution.

`images/logo.bmp`

**Comment by mxve** [comment]
The launcher can overwrite files just fine, it does so on every single update.
There is some kind of file-locking or permission issue going on, which I've personally only seen with pirated copies as you seem to be using too. Thus my answer is: Use a legitimate copy, we do not condone nor support piracy.

**Comment by pickles976** [comment]
Ok sounds good, if I make a PR for this issue, would it be merged?

**Comment by mxve** [comment]
Sure

**Comment by pickles976** [comment]
Rust appears unable to delete modified files like custom splash screens, so I will close this issue with no resolution.
