### ISSUE TITLE
Inquiry about failed download file after executing alterware-launcher(v0.8.4).

### ISSUE THREAD

**Issue by wonheui** [mxve/alterware-launcher#163]
Hello.
Thank you for letting me play a good game.
After a long time...I tried to run the alterware-launcher(v0.8.4) program from the installed folder to play the game, but an error occurred, so I am contacting you.
As shown in the picture, it says "Failed to download file J:/++ Games Download ++/++ Games Play ++/[No installation] Call of Duty Modern Warfare 2 + IW4x/main/iw_dlc4_01.iwd".
What should I do?
Or can you share the "iw_dlc4_01.iwd" file?
I always appreciate it.
Thank you for your hard work.

![Failed to download file](https://github.com/user-attachments/assets/0b8d109e-84e6-4c1f-81aa-a79891cf4cb9)

**Comment by diamante0018** [comment]
Please read this [document](https://github.com/mxve/alterware-launcher?tab=readme-ov-file#-installation), you failed on point one therefore all support requests from pirates are reject at point blank. Good luck with your attempts to install the game on your own.
