### ISSUE TITLE
[Offline mode]: Possible ideas and solutions

### ISSUE THREAD

**Issue by diamante0018** [mxve/alterware-launcher#164]
Apparently, the XLabs launcher did allow for users to launch the various clients without an internet connection.
This was done by basically hard coding everything and having the dynamic data shipped with the launcher itself which was cached on localappdata folder.

Without an internet connection the launcher had the game data available and the dynamic game info downloaded on the machine anyway, allowing the launcher to open and launch the games. That is how possibly there are still people on the XLabs version of all of our clients, unaware of anything, they can still open up those games with that launcher and be unaware that the clients are in localappdata...

Possible solution:

Without an internet connection the AW launcher will attempt to do nothing and gives out an error message. This leaves a user with no motivation to investigate further, no technical knowledge, without an internet connection to give up. (https://discord.com/channels/1110531063161299074/1145458108190163014/1315291634409148517)

AW can implement the same strategy as the XLabs launcher, that is, instead of reading from the cdn and discarding the data after it's done using it, it could download it to an appdata folder and cache everything it needs to function (json files). Without an internet connection it shall be able to infer that it should use the cached data (if it exists after at least one successful run with internet). detect the game/client and try to open it.

It should also improve error handling saying that it should be run with an internet connection at least once if no cached data is detected. and improved error messaging if some missing client files like the necessary dlls and exe are still missing (internet was cut off during first download?)

**Comment by mxve** [comment]
https://github.com/mxve/alterware-launcher/commit/2d84c514a73fad1a244fe42abb84becf90ae3089
