### ISSUE TITLE
Windows Defender 

### ISSUE THREAD

**Issue by jmtn** [mxve/alterware-launcher#44]
When agreeing to "Download bonus content" in the launcher, Windows Defender flags iw4-sp.exe as :"Trojan:Win32/Wacatac.H!ml"

![image](https://github.com/mxve/alterware-launcher/assets/55904761/ce2f227c-79f3-4013-93b4-7e9d0f9af231)

**Comment by mxve** [comment]
This is a false positive detection on the executable of the singleplayer client.
If you only intend to play multiplayer you can ignore it, if you want to play singleplayer you'd have to add an exception to windows defender
https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26
