### ISSUE TITLE
IW4x (and IW4-sp) always auto-update and install the same files but never launch the game

### ISSUE THREAD

**Issue by Zizoplays1** [mxve/alterware-launcher#86]
As the title says, whenever i try to launch this game using the alterware launcher or double clicking from the files, it just goes to auto-update and install the same files, they are:

-IW4x_00.iwd
-IW4x_01.iwd
-iw4x/html/script.js
-zone/patch/iw4x_patch_mp.ff
-zone/patch/iw4x_localized_english.ff
-zone/patch/iw4x_code_post_gfx_mp.ff
-zone/patch/iw4x_ui_mp.ff
-iw_dlc10-00.iwd

even after waiting for these files to download, the game seemingly never launches at all, is there any solution?

**Comment by mxve** [comment]
Does the Launcher Close? If not Take a Screenshot of the Output.
Try running as admin, If that doesn't help delete .sha-sums and the files its redownloading manually before trying again.

**Comment by Zizoplays1** [comment]
It does close
I will try running it as admin very soon, kinda busy atm, I also deleted the files it keeps downloading but never really tried deleting the .sha_sums file, will see that soon incase running the launcher as an admin doesn't do a thing. Thanks for replying btw!

**Comment by mxve** [comment]
It closing means its crashing, open a command prompt / termianl in the game folder and run the launcher from it to see the output

**Comment by Zizoplays1** [comment]
So even trying to run as administrator and deleting all the files again including the shia.sums file doesn't work

How can I open a command prompt/terminal in the game folder? Do you mean like run CMD and type open the alterware launcher or what?

**Comment by mxve** [comment]
> Do you mean like run CMD and type open the alterware launcher or what?

Late reply, but yes
